### ISSUE TITLE
We should default to `autoCreate: false`

### ISSUE THREAD

**Issue by feliun** [infinitaslearning/ez-pubsub#5]
So topics/subscriptions are not created on the fly. People need to favour https://github.com/infinitaslearning/infra-liber-servicebus-config in order to provision topics/subscriptions

**Comment by PeterAronZentai** [comment]
Fixed in this: https://github.com/infinitaslearning/ez-pubsub/commit/7bbea7ea6e8ce2a9ac6260d77b5c4217359006bb
